version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
      python: 3.8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - pip3 install pymysql requests -t .
      - zip -r bundle.zip .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - bundle.zip
    - appspec.yml
